/*
 * TIMER1_Config.h
 *
 *  Created on: Sep 6, 2023
 *      Author: 00214
 */

#ifndef DRIVER_MCAL_TIMER1_TIMER1_CONFIG_H_
#define DRIVER_MCAL_TIMER1_TIMER1_CONFIG_H_

#define TIMER1_PRES   				 TIMER1_PRE_8

#define TIMER1_MODE    				 TIMER1_FAST_PWM_TOP_ICR1

#define TIMER1_OC0_PIN_STATE_CHA     TIMER1_FAST_PWM_CLEAR_CTC_SET_TOP_CHA

#define TIMER1_OC0_PIN_STATE_CHB	 TIMER1_DISCONNECTED_CTC_OC0_CHB

// write freq in KHZ
#define TIMER1_F_CPU  (1000UL)



#endif /* DRIVER_MCAL_TIMER1_TIMER1_CONFIG_H_ */
